### PR TITLE
Pass an access token for private repositories

### PR DESCRIPTION
**Pull request by jayperryworks**
Thanks so much for making this npm package! It was a huge help for me when I ran into the Introspection issue while trying to fetch my slices. Unfortunately, my Prismic repo is private and requires an access token. I took a stab at modifying your script so that it can pass an optional token to the endpoints - appreciate your thoughts.

- It accepts a path to a text file (e.g. `./.prismic-token`) containing nothing but your token string.
- I'm not super familiar with the `command` lib - hopefully I set up the option right...
- I tested this locally with my own Prismic repo and it worked, but I haven't tested much beyond that.

### CODE REVIEW

**Comment by madeleineostoja** [comment]
Hey thanks! I think a better approach might be setting an environment variable, rather than reading from a file? Most CI and local dev environments can inject variables for you, and if running manually you can just prefix with an env declaration, like 


```
PRISMIC_ACCESS_TOKEN=xxxx prismic-apollo-introspect
```

**Comment by jayperryworks** [comment]
Oh, that's a good idea! I'll make some tweaks, prob a little later this week.

**Comment by jayperryworks** [comment]
Sorry it took me awhile to get back to this. After some reading and experimenting, I got the environment variable working locally. I added some notes to the README also.

**Comment by madeleineostoja** [comment]
👍 LGTM, Thanks!

**Pull request merged**
